### PR TITLE
Do not replace leading spaces per nbsp. We are in a pre block. And it's breaking some code.

### LINKED ISSUE #263: Indenting code produces unusable code on some platforms
`Pod::Elemental::Transformer::SynHi` transforms leading `\s` into `&nbsp;`. Some platforms turn `&nbsp;` into a regular space `0x20`, but Firefox on Windows preserves it as the UTF-8 bytes `C2A0`.

It appears `Pod::Elemental::Transformer::SynHi`'s behavior is intentional for code in feeds:
https://github.com/rjbs/Pod-Elemental-Transformer-SynHi/blob/master/lib/Pod/Elemental/Transformer/SynHi.pm#L228-L231

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
It's intended to fix https://github.com/perladvent/Perl-Advent/issues/263

### CODE REVIEW

**Comment by thibaultduponchelle** [comment]
Please note:
- This one is more risky
- We prefer website over feed readers

**Comment by thibaultduponchelle** [comment]
@G4Vi

**Comment by G4Vi** [comment]
If feed reader support isn't needed, fix LGTM to me, thank you!

**Review by oalders — APPROVED** [review]

**Comment by thibaultduponchelle** [comment]
Seems like MetaCPAN had similar issue and fix some time ago: https://github.com/metacpan/metacpan-web/pull/2822

**Pull request merged**
