### PR TITLE
Simplify wrapping HTML around code blocks

### PR DESCRIPTION
**Pull request by thibaultduponchelle**
The current code is wrapping code inside a bit too much elements (in particular a table) which is a bit problematic because all those elements are bringing different layout and default css style.

The purpose of this change is to simplify wrapping code to the maximum (pre + code + class).

This pull request is a noop at the moment, it can be merged safely (in other words, I'm preparing you that I will maybe merge it without review/approvals 😃)

The overall idea is to use this forked version of the module in order to fix the code block overflow issue we have with Perl Advent calendar.

### CODE REVIEW

**Comment by thibaultduponchelle** [comment]
@oalders @openstrike

**Comment by thibaultduponchelle** [comment]
With changes https://github.com/perladvent/WWW-AdventCalendar/pull/4 and something like https://github.com/thibaultduponchelle/Perl-Advent/commit/1e0eb945954208757d56b522c6a we can get the code block fixed and close https://github.com/perladvent/Perl-Advent/issues/266

## Before
layout-problem-code-blocks


## After
fixed-code-blocks

(please note the scroll bar)

It is at the cost of dropping line numbers... but they also have issues (even more on smartphones) and needed to be fixed...

**Comment by thibaultduponchelle** [comment]
I tried my best to go with a change of CSS only in WWW::AdventCalendar (in other words avoid forking this module) but I was never able to achieve it 😢

**Review by oalders — APPROVED** [review]
I did notice issues with the line numbers as well. Nice to see you chipping away at this problem. 😄

**Comment by oalders** [comment]
> I tried my best to go with a change of CSS only in WWW::AdventCalendar 

I guess we could also post-process the files after build, but I'm not sure if that's any better.

**Pull request merged**
